config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#top"
  
  resources :products,except: :show do
    
    
      get 'top'
      get 'find_videos'
      get 'week_one'
      get 'week_two'
      get 'week_three'
      get 'week_four'
      get 'month_one'
      get 'month_two'
      get 'exchange'
    end
  namespace :api do
    resources :products, only: :new, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :post, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  protect_from_forgery :except => ["new"]
  def new
    post = Post.all
    post_id = params[:id]
    @posts = post.includes(:user).where("id > ?", post_id)
      
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  protect_from_forgery :except => ["create","update"]
  def top
  end

  def index
  end

  def exchange
    @posts = Post.includes(:user).order("created_at ASC")
  end

  def new
    @post = Post.new
    @posts = Post.includes(:user).order("created_at ASC")
  end

  def create
    @post = Post.create(post_params)
    @post.save
  end

  def edit
    @post = Post.find(params[:id])
    @posts = Post.includes(:user)
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
    format.json{
    if @post.update!(post_params)
       render json: @post
    else
      head :bad_request
    end
    }
  end
  end

  def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to new_product_path
  end
  private
  def post_params
    params.require(:post).permit(:post,:image).merge(user_id: current_user.id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_header.html.haml
%header
  %ul.link_tabs__box
    .link_tabs__box__top
      =link_to "トップ",root_path,class: 'top_tab'
    .link_tabs__box__training
      =link_to "トレーニングRoom",products_path,class:'training_tab'
    - if user_signed_in?
      .link_tabs__box__exchange
        =link_to "情報交換ページへ",new_product_path,class:'exchange_tab'
      .link_tabs__box__logout
        =link_to "ログアウト",destroy_user_session_path, class:'logout_tab',method: :delete
    - else
      .link_tabs_box__login
        = link_to "ログイン",new_user_session_path,class:'login_tab'
      .link_tabs_box__regisration
        = link_to "新規登録",new_user_registration_path,class:'regisration_tab'
        

app/views/products/_message.html.haml
.show
  .show__messages
    .show__messages__message
      -@posts.each do |post|
        .show__messages__message__namebox{"data-post-id": "#{post.id}"}
          .show__messages__message__namebox__number{id:"jsCommentLabel-#{post.id}"}
            = post.id
          .show__messages__message__namebox__name
            ="#{post.user.nickname}："
          .show__messages__message__namebox__time
            = post.created_at
          

          - if user_signed_in? && current_user.id == post.user_id
            %span.js-edit-comment-button{"data-comment-id": "#{post.id}",id:"authenticity_token"}  
              %i.fas.fa-edit.text-primary
            =link_to  product_path(post.id),method: :delete do
              %i.fas.fa-trash-alt
        .show__messages__message--comment{id:"hogehoge-#{post.id}"}
          = post.post
        %div{class: "show__messages__message__editbox",id: "js-comment-#{post.id}"}
          %p{id: "js-comment-label-#{post.id},post.body"}
          %p.text-danger{id: "js-comment-post-error-#{post.id}"}
          %textarea{class:"form-control.comment-post-error-post.body",id: "js-textarea-comment-#{post.id}", style: "display: none;"}
        %div{class:"edit__btnbox",id:"js-comment-button-#{post.id}",style: "display: none;"}
          %button.btn.btn-light.comment-cancel-button{"data-cancel-id": "#{post.id}"}キャンセル
          %button.btn.btn-right.comment-update-button{"data-update-id": "#{post.id}"}更新する

        .show__messages__message__image
          - if post.image?
            = image_tag post.image.url, :size =>'410x300'

app/views/products/edit.html.haml
.edit
  投稿の編集
  .show__messages__namebox
    = form_with model: @post, id: 'edit_form',url: product_path,local: true do |form|
      = form.text_area :post,class:"footer__comment_box__text"
      = form.submit"変更する",class:"footer__comment_box__btn"

app/views/products/exchange.html.haml
= render 'message'
.show__main__btn
  =link_to 'コメントする',new_product_path

app/views/products/index.html.haml
.index_main
  .top_title トレーニングROOM
  =render 'header'
  .link_pagebox
    .note　ご自身のトレーニング期間に応じてリンク先に飛んでください。次に移るのが厳しいなと思うときは慣れるまでそのメニューで大丈夫です。
    .week_one 
      = link_to "1週間目のトレーニングメニューへ",week_one_products_path,class:'week_one__link'
    .week_two
      = link_to "2週間目のトレーニングメニューへ",week_two_products_path,class:'week_two__link'
    .week_three
      = link_to "3週間目のトレーニングメニューへ",week_three_products_path,class:'week_three__link'
    .week_four
      = link_to "4週間目のトレーニングメニューへ",week_four_products_path,class:'week_four__link'
    .month_one
      = link_to "1ヶ月目〜のトレーニングメニューへ",month_one_products_path,class:'month_one__link'
    .month_two
      = link_to "2ヶ月目〜のトレーニングメニューへ",month_two_products_path,class:'month_two__link'

app/views/products/month_one.html.haml
.week_one1
  .text_box_1week 1ヶ月目トレーニング
  = render 'header'
  .content_1week_main
    .content_1week_main
      .content_1week_main__readiness 
        .content_1week_main__readiness__header 心構え
        %li.content_1week_main__readiness__text
          いつまでに、何のために痩せたいのか明確にしましょう！
        %li.content_1week_main__readiness__text 
          同じメニューだと身体が順応するので違う動画などで他の部分の筋肉の活性化をするといいでしょう
        %li.content_1week_main__readiness__text
          食事は消費カロリー＞摂取カロリーが基本です。
        %li.content_1week_main__readiness__text
          お腹の脂肪を落としたい方は、糖質を制限するのではなく脂質に意識を向けて摂取しないようにしましょう。（少しは取らないと便が出ないので注意してください）
      .content_1week_main__training
        .content_1week_main__training__header トレーニング内容
        .content_1week_main__training__header__point
          【この中の３つくらいをセレクトしてやっていくと良いです。できない日はストレッチだけでもやってみてください】
        %li.content_1week_main__training__menu
          【４分間で確実に痩せる‼】痩せたい人だけ体幹サーキット ‼【プランクサーキット】
        %li.content_1week_main__training__menu
          【10分】世界一痩せるスクワット！
        %li.content_1week_main__training__menu
          【10分】パンチで脂肪を1kg落とす！全身の脂肪燃焼有酸素運動！
        %li.content_1week_main__training__menu
          ５キロウォーキング（速歩き　35分前後で歩いていました。）
        %li.content_1week_main__training__menu-new
          最強プランク１３種を紹介！【各動き30秒ずつ】　←New ！！
        %li.content_1week_main__training__menu-new
          【10分】静かに汗だく！脂肪燃焼がヤバい！ | Muscle Watching　　←New ！！
        %li.content_1week_main__training__menu-new
          胸を大きくする３分間６種類の最強自重胸トレメニュー！【効かない訳が無いトレ】大胸筋トレーニング 筋トレ　　←New ！！
      .content_1week_main__meal
        .content_1week_main__meal__header 食事内容
        %li.content_1week_main__meal__menu
          【マッスルグリル】沼
        %li.content_1week_main__meal__menu
          低糖質麦芽コーヒーor水
        %li.content_1week_main__meal__menu
          キットカット１枚
        %li.content_1week_main__meal__menu-cheat
          チートデー1日（カロリー脂質等気にせず何でも食べてOKな日）
      .content_1week_main__cheat
        .content_1week_main__cheat__header
          チートデーについて
        .content_1week_main__cheat__day
          1日だけ好きなものを全力で食べましょう。罪悪感を持たずに食べることが大切です。
        .content_1week_main__cheat__day
          脂質が多いものはやめたほうがいいとか体脂肪率20%以上はやる必要がないとか一般的に言われていますが気にしちゃいけません。
        .content_1week_main__cheat__day
          精神的に安定するために行うものであり、ガス抜きが大事です。
        .content_1week_main__cheat__day
          私はジャンクを食べたくなり、マクドナルドに行き
        .content_1week_main__cheat__day
          ビッグマック、ダブルチーズバーガー、ポテナゲ特大、爽健美茶、三角チョコパイ２つ、ダブルチョコメルツ
        .content_1week_main__cheat__day
          上記を食べました。恐ろしい糖質量と脂質量ですね　笑　
        .content_1week_main__cheat__day
          おそらく脂質は200〜300gほど摂取していると思います。私の1日の脂質必要摂取量は55gなので6倍近く摂取していますが3日でもとに戻りました。
        .content_1week_main__cheat__day
          一日のトレーニングで体重が減らないように、一日の食事で太ることもありません。積み重ねなければ大丈夫です。
        .content_1week_main__cheat__day
          チートデーの日にもトレーニングを行い、翌日からは元の食事に戻しましょう！
      .content_1week_main__readiness
        .content_1week_main__readiness__header
          反省点や振り返り（一ヶ月の振り返り）
        .content_1week_main__readiness__menu
          ここまで来ると習慣化しているので、ほぼルーティーンと化していると思います。
        .content_1week_main__readiness__menu
          この一ヶ月は飽きなどが来ないように工夫しました。メニューを増やしたり、自分の体を見てどこを鍛えたいか等模索してメニューを決めました。
        .content_1week_main__readiness__menu
          新規で追加したメニューはどれもハードなものばかりです。
        .content_1week_main__readiness__menu
          流石にきつすぎるので、初心を思い出しきついものは負荷が軽くなるように工夫しながら行いました。
        .content_1week_main__readiness__menu
          うっすら腹筋が見えてき始めて今後を考えるのにワクワクしていました。
        .content_1week_main__readiness__menu
          また食事が沼だけなのに飽きる人は飽きると思うので消費カロリーの範囲内で好きなものを食べても問題ありません。
        .content_1week_main__readiness__menu
          1ヶ月も食事を低脂質にするとさすがに、我慢の限界が来てしまうので自分のタイミングでチートデーを設定しましょう。翌日からの励みになります。
        .content_1week_main__readiness__menu
          この頃に少しずつ痩せ始め、71kg→65kgになりました。
      .content_1week_main__training__commentary
        .content_1week_main__training__commentary__header
          トレーニング動画紹介【追加あり】
        .content_1week_main__training__commentary__movie 
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/19ZBZPT1CnA", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          プランクです。特にジェットゆうさんの動画は短く負荷もそこまで高くないため初心者におすすめです。スクワットがつらすぎるという方はこれだけでも欠かさずやりましょう。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/joNzM16CASk", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          スクワットは、MuscleWatchingさんの動画をおすすめしています。
        .content_1week_main__training__commentary__movie-comment
          女性目線でエクササイズをしてくださることが多いyoutuberさんです。
        .content_1week_main__training__commentary__movie-comment
          肩甲骨の動きを意識して、しっかりと行うとよいです。
        .content_1week_main__training__commentary__movie-comment
          この段階だとこのメニューはほぼ翌日に疲労なども残らないと思います。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/3PDy_bkpRSs", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          ボクシングの動きです、追い込み過ぎなければ非常に楽しくトレーニングできるのでおすすめです。
        .content_1week_main__training__commentary__movie-comment
          この段階だと回数を増やして見たりしていいと思います。順番は順不同で大丈夫ですが、有酸素要素が大きいのでスクワットの後にやったほうがいいと思います。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/hns0ZEl3fVY", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          このアプリで紹介するメニューの中で間違えなく最強のトレーニングです。
        .content_1week_main__training__commentary__movie-comment
          めちゃくちゃきついですが身体がみるみる変わっていきます。
        .content_1week_main__training__commentary__movie-comment
          メトロンさんは上級者向けなのできつい方はジェットゆうさんの動画をおこなってください
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/jXkcsC7fjYU", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          これも最高にきついです。トレーナーさんもバテバテになってます　笑　
        .content_1week_main__training__commentary__movie-comment
          背中や腹筋の横などを鍛えたいときはこれがおすすめです。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/6JIRtnZyqwA", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          これは胸の脂肪がだらしないなと思った方におすすめしています。　
        .content_1week_main__training__commentary__movie-comment
          胸を張るようにして行うとよいです。最強に胸筋がつきますが、女性にはおすすめしません。
      =link_to "2ヶ月目〜トレーニングへ移動する",month_two_products_path,class:"next-link"

app/views/products/month_two.html.haml
.week_one1
  .text_box_1week 2ヶ月目トレーニング
  = render 'header'
  .content_1week_main
    .content_1week_main
      .content_1week_main__readiness 
        .content_1week_main__readiness__header 心構え
        %li.content_1week_main__readiness__text
          いつまでに、何のために痩せたいのか明確にしましょう！（私の場合は８月に格闘技を始めるために少し痩せたいでした）
        %li.content_1week_main__readiness__text 
          同じメニューだと身体が順応するので違う動画などで他の部分の筋肉の活性化をするといいでしょう
        %li.content_1week_main__readiness__text
          食事は消費カロリー＞摂取カロリーが基本です。
        
      .content_1week_main__training
        .content_1week_main__training__header トレーニング内容
        .content_1week_main__training__header__point
          【この中の３つくらいをセレクトしてやっていくと良いです。できない日はストレッチだけでもやってみてください】
        %li.content_1week_main__training__menu
          【４分間で確実に痩せる‼】痩せたい人だけ体幹サーキット ‼【プランクサーキット】
        %li.content_1week_main__training__menu
          【10分】世界一痩せるスクワット！
        %li.content_1week_main__training__menu
          【10分】パンチで脂肪を1kg落とす！全身の脂肪燃焼有酸素運動！
        %li.content_1week_main__training__menu
          最強プランク１３種を紹介！【各動き30秒ずつ】
        %li.content_1week_main__training__menu
          【10分】静かに汗だく！脂肪燃焼がヤバい！ | Muscle Watching
        %li.content_1week_main__training__menu
          胸を大きくする３分間６種類の最強自重胸トレメニュー！【効かない訳が無いトレ】大胸筋トレーニング 筋トレ
        %li.content_1week_main__training__menu
          ５キロウォーキング（速歩き　33分前後で歩いていました。）
        %li.content_1week_main__training__menu-new
          【体幹！腸腰筋！逆腹筋サーキット‼】逆腹筋を取り入れた簡単激やせサーキット‼【４分間‼】【無駄な筋肉付けません!!】　　←New ！！
        %li.content_1week_main__training__menu-new
          成人からの！体が柔らかくなる軟体ストレッチ法を紹介【日々筋トレ漬け体ガチガチにも必見】　　←New ！！
        %li.content_1week_main__training__menu-new
          開脚できるようになるストレッチ！【2週間で開脚ベターっになる方法】　←New ！！
      .content_1week_main__meal
        .content_1week_main__meal__header 食事内容
        %li.content_1week_main__meal__menu
          味噌汁＋納豆（毎食）
        %li.content_1week_main__meal__menu
          カロリーハーフのネスカフェ
        %li.content_1week_main__meal__menu
          鶏肉
        %li.content_1week_main__meal__menu
          もうやんカレー
        %li.content_1week_main__meal__menu
          居酒屋　週３回ペース
      .content_1week_main__readiness__success
        .content_1week_main__readiness__header反省点や振り返り（一ヶ月の振り返り）
        .content_1week_main__readiness__success__menu
          この月はプライベートで色々あり
        .content_1week_main__readiness__success__menu
          結果として外食が非常に多かったです。ご飯を作ることもあまりしませんでした。
        .content_1week_main__readiness__success__menu
          考え方として変わったことは、味噌汁と納豆を食事の最初に取り入れることです。
        .content_1week_main__readiness__success__menu
          これのおかげでお腹いっぱい食べたとしても大した量を食べなくて済みました。
        .content_1week_main__readiness__success__menu
          納豆のおかげで腸内環境が整うのも一石二鳥でした。体調が抜群に良くなったと思います。
        .content_1week_main__readiness__success__menu
          飲み物に関しても、豆乳をずっと飲んできましたが、カロリーハーフのネスカフェと対してカロリーが変わらないのと納豆で大豆を摂取しているので変更にいたりました。
        .content_1week_main__readiness__success__menu
          筋トレ休みの日にやるメニューとしてストレッチも追加しています。
        .content_1week_main__readiness__success__menu
          飲みに行った日はストレッチ、そうじゃない日はトレーニングと日常の付き合いの波にも対応できるトレーニングとなっています。
        .content_1week_main__readiness__success__menu
          また週３回で外食していたにも関わらず、痩せていったので、ここまでトレーニングを続けられている方は相当太りにくくなっていることを実感できると思います。
        .content_1week_main__readiness__success__menu
          ただ、注意してほしいのはここまで来るとトレーニングをサボっても体重が減少します。
        .content_1week_main__readiness__success__menu
          なぜなら、筋肉が減少するからです。何もしないでも痩せる！と思ってサボっていると脂肪がついてまた太るので注意してください。
        .content_1week_main__readiness__success__menu
          この段階で71kg→63kgになりー８キロのダイエットに成功しました！
      .content_1week_main__training__commentary
        .content_1week_main__training__commentary__header トレーニング動画紹介【追加あり】
        .content_1week_main__training__commentary__movie 
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/19ZBZPT1CnA", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          プランクです。特にジェットゆうさんの動画は短く負荷もそこまで高くないため初心者におすすめです。スクワットがつらすぎるという方はこれだけでも欠かさずやりましょう。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/joNzM16CASk", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          スクワットは、MuscleWatchingさんの動画をおすすめしています。女性目線でエクササイズをしてくださることが多いyoutuberさんです。
        .content_1week_main__training__commentary__movie-comment
          肩甲骨の動きを意識して、しっかりと行うとよいです。
        .content_1week_main__training__commentary__movie-comment
          この段階だとこのメニューはほぼ翌日に疲労なども残らないと思います。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/3PDy_bkpRSs", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          ボクシングの動きです、追い込み過ぎなければ非常に楽しくトレーニングできるのでおすすめです。
        .content_1week_main__training__commentary__movie-comment
          この段階だと回数を増やして見たりしていいと思います。順番は順不同で大丈夫ですが、有酸素要素が大きいのでスクワットの後にやったほうがいいと思います。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/hns0ZEl3fVY", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          このアプリで紹介するメニューの中で間違えなく最強のトレーニングです。めちゃくちゃきついですが身体がみるみる変わっていきます。
        .content_1week_main__training__commentary__movie-comment
          メトロンさんは上級者向けなのできつい方はジェットゆうさんの動画をおこなってください
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/jXkcsC7fjYU", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          これも最高にきついです。トレーナーさんもバテバテになってます　笑　背中や腹筋の横などを鍛えたいときはこれがおすすめです。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/6JIRtnZyqwA", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          これは胸の脂肪がだらしないなと思った方におすすめしています。　胸を張るようにして行うとよいです。最強に胸筋がつきます。女性にはおすすめしません。
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/Hoix4GAvGnU", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          たった状態での体感トレーニングになります。筋肉が硬いと全く足が上がりません。本当に笑っちゃうくらい上がらないのでぜひやってみてください！
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/WyQjIAifWII", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          上記の問題を解決すべく、敬愛するメトロンブログさんの動画でストレッチを行いました。呼吸が大事です。ただ、やりすぎると首を痛めるので注意してください
        .content_1week_main__training__commentary__movie
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/Re5FPU5_37g", :width => "560"}
        .content_1week_main__training__commentary__movie-comment
          こちらの動画は、メトロンさんのものより優しい内容となっています。ぜひこちらも試してみてください。メトロンさんの動画出てきた呼吸法をつかって行うとなお良いです
      =link_to "トレーニングルームに戻る",products_path,class:"next-link"

app/views/products/new.html.haml
.new_main
  .show__toplogo 情報交換ROOM
  = render 'header'
  = render 'message'
  .footer
    .footer__comment_box
      = form_with model: Post.new, id: 'new_form',url: products_path,local: true do |form|
        = form.text_area :post,placeholder:"例)1週間目です。徐々に筋トレになれてきました。",class:"footer__comment_box__text"
        = form.file_field :image
        = form.submit"投稿する",class:"footer__comment_box__btn"

app/views/products/top.html.haml
.top_main
  .title
    %h1 ３ヶ月で8キロ痩せたトレーニングと食事メニュー
  .content
    %h2.introduction1　自己紹介
    %p.introduction1__main  自称筋肉質だからという謎の自信をもっていたためプログラミングを学びながらお菓子ばっかり食べていたら身長155cmで体重が71kgになる。
    %p.introduction1__main  鏡に映った自分のお腹を見て絶望ダイエットを決意。
    %p.introduction1__main  日々のトレーニングと食事を見直すことで8kgのダイエットに成功しました。現在も継続中です。
    %p.introduction1__main  多くの人の生活を便利で豊かにしたいという思いでプログラミングという道を選びました。
    %p.introduction1__main  このアプリがその第一歩になればと思います。
    %h2.introduction1　運動歴
    %p.introduction1__main  中学〜高校１年生まで陸上競技（短距離）を専門に行う
    %p.introduction1__main  高校2年からは柔道部に入部、入部後メキメキ成長し３ヶ月目に大会初出場で地区３位に入賞する。
    %p.introduction1__main  アームレスリング元世界王者の道場で1年アームレスリングを教わる
    %p.introduction1__main  初めての大会で70キロ以下の部に出場、なぜか90キロ台のおじさんと試合になり入賞を逃す。
    %p.introduction1__main  その後、約10年間運動からは離れていました。
    %p.introduction1__main  基礎体力はある方だと思います。
    %h2.introduction1　アプリを作った目的
    %p.introduction1__main  ダイエット情報が多い中で、効果のあったやり方をお伝えして少しでも痩せたい人の力になれればと思い作成しました。
    %p.introduction1__main  情報過多で結局どのように痩せればいいのか、何をしたらいいのかが、非常に分かりにくくなっているのが現状ではないかと思います。
    %p.introduction1__main  このコンテンツで自分の中の失敗や成功などをお伝えし、多くの人に痩せる近道をしていただき、理想の体になってもらえたら幸いです。
    %p.introduction1__main  また、コメントを通じて情報交換などを行い。ともに成長していけたらと思っています。

    .title__link
      = link_to "トレーニングメニューページへ移動",products_path ,class:"link_top"
 